name: CI

on:
  push:
    branches: ["trunk"]
  pull_request:

jobs:
  ci:
    uses: danielriddell21/github-actions/.github/workflows/ci.yaml@v1
    permissions:
      contents: write
    with:
      ebiten: true
      test-command: xvfb-run -a go test -coverprofile=coverage.txt ./...
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
      tag-token: ${{ secrets.PANDEMONIUM_TOKEN }}
